//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIA_PLATILLO
    {
        public byte DIA { get; set; }
        public byte PLATILLO { get; set; }
        public Nullable<System.DateTime> MODIFICACION { get; set; }
    
        public virtual DIA DIA1 { get; set; }
        public virtual PLATILLO PLATILLO1 { get; set; }
    }
}
