//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADOR()
        {
            this.CONVENIO_EMPRESA = new HashSet<CONVENIO_EMPRESA>();
        }
    
        public byte EMPLEADOR_ID { get; set; }
        public string NOMBRE { get; set; }
        public string APPATERNO { get; set; }
        public string APMATERNO { get; set; }
        public int RUT { get; set; }
        public byte TIPO_USUARIO_ID { get; set; }
        public byte USUARIO_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONVENIO_EMPRESA> CONVENIO_EMPRESA { get; set; }
        public virtual USUARIO_TIPO_USUARIO USUARIO_TIPO_USUARIO { get; set; }
    }
}
