//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EntidadesAlimentos : DbContext
    {
        public EntidadesAlimentos()
            : base("name=EntidadesAlimentos")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<CLIENTE_PEDIDO> CLIENTE_PEDIDO { get; set; }
        public virtual DbSet<CONVENIO_EMPRESA> CONVENIO_EMPRESA { get; set; }
        public virtual DbSet<DETALLE_VENTA> DETALLE_VENTA { get; set; }
        public virtual DbSet<DIA> DIA { get; set; }
        public virtual DbSet<DIA_PLATILLO> DIA_PLATILLO { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADO { get; set; }
        public virtual DbSet<EMPLEADOR> EMPLEADOR { get; set; }
        public virtual DbSet<ESTADO_PEDIDO> ESTADO_PEDIDO { get; set; }
        public virtual DbSet<FORMA_PAGO> FORMA_PAGO { get; set; }
        public virtual DbSet<PEDIDO> PEDIDO { get; set; }
        public virtual DbSet<PEDIDO_PLATILLO> PEDIDO_PLATILLO { get; set; }
        public virtual DbSet<PLANILLA_TRABAJADORES> PLANILLA_TRABAJADORES { get; set; }
        public virtual DbSet<PLATILLO> PLATILLO { get; set; }
        public virtual DbSet<TIPO_USUARIO> TIPO_USUARIO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<USUARIO_TIPO_USUARIO> USUARIO_TIPO_USUARIO { get; set; }
        public virtual DbSet<VENTA> VENTA { get; set; }
    
        public virtual int PROCEDURE_ACTUALIZAR_EMPLEADO(string p_NOMBRE_USUARIO, string p_CONTRASENA, Nullable<decimal> p_TIPO_USUARIO, Nullable<decimal> p_USUARIO, string p_NOMBRE, string p_APPATERNO, string p_APMATERNO, Nullable<decimal> p_RUT)
        {
            var p_NOMBRE_USUARIOParameter = p_NOMBRE_USUARIO != null ?
                new ObjectParameter("P_NOMBRE_USUARIO", p_NOMBRE_USUARIO) :
                new ObjectParameter("P_NOMBRE_USUARIO", typeof(string));
    
            var p_CONTRASENAParameter = p_CONTRASENA != null ?
                new ObjectParameter("P_CONTRASENA", p_CONTRASENA) :
                new ObjectParameter("P_CONTRASENA", typeof(string));
    
            var p_TIPO_USUARIOParameter = p_TIPO_USUARIO.HasValue ?
                new ObjectParameter("P_TIPO_USUARIO", p_TIPO_USUARIO) :
                new ObjectParameter("P_TIPO_USUARIO", typeof(decimal));
    
            var p_USUARIOParameter = p_USUARIO.HasValue ?
                new ObjectParameter("P_USUARIO", p_USUARIO) :
                new ObjectParameter("P_USUARIO", typeof(decimal));
    
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("P_NOMBRE", p_NOMBRE) :
                new ObjectParameter("P_NOMBRE", typeof(string));
    
            var p_APPATERNOParameter = p_APPATERNO != null ?
                new ObjectParameter("P_APPATERNO", p_APPATERNO) :
                new ObjectParameter("P_APPATERNO", typeof(string));
    
            var p_APMATERNOParameter = p_APMATERNO != null ?
                new ObjectParameter("P_APMATERNO", p_APMATERNO) :
                new ObjectParameter("P_APMATERNO", typeof(string));
    
            var p_RUTParameter = p_RUT.HasValue ?
                new ObjectParameter("P_RUT", p_RUT) :
                new ObjectParameter("P_RUT", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROCEDURE_ACTUALIZAR_EMPLEADO", p_NOMBRE_USUARIOParameter, p_CONTRASENAParameter, p_TIPO_USUARIOParameter, p_USUARIOParameter, p_NOMBREParameter, p_APPATERNOParameter, p_APMATERNOParameter, p_RUTParameter);
        }
    
        public virtual int PROCEDURE_CREAR_CUENTA(string p_NOMBRE_USUARIO, string p_CONTRASENA, Nullable<decimal> p_TIPO_USUARIO, string p_NOMBRE, string p_APPATERNO, string p_APMATERNO, Nullable<decimal> p_RUT, ObjectParameter p_RETORNO)
        {
            var p_NOMBRE_USUARIOParameter = p_NOMBRE_USUARIO != null ?
                new ObjectParameter("P_NOMBRE_USUARIO", p_NOMBRE_USUARIO) :
                new ObjectParameter("P_NOMBRE_USUARIO", typeof(string));
    
            var p_CONTRASENAParameter = p_CONTRASENA != null ?
                new ObjectParameter("P_CONTRASENA", p_CONTRASENA) :
                new ObjectParameter("P_CONTRASENA", typeof(string));
    
            var p_TIPO_USUARIOParameter = p_TIPO_USUARIO.HasValue ?
                new ObjectParameter("P_TIPO_USUARIO", p_TIPO_USUARIO) :
                new ObjectParameter("P_TIPO_USUARIO", typeof(decimal));
    
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("P_NOMBRE", p_NOMBRE) :
                new ObjectParameter("P_NOMBRE", typeof(string));
    
            var p_APPATERNOParameter = p_APPATERNO != null ?
                new ObjectParameter("P_APPATERNO", p_APPATERNO) :
                new ObjectParameter("P_APPATERNO", typeof(string));
    
            var p_APMATERNOParameter = p_APMATERNO != null ?
                new ObjectParameter("P_APMATERNO", p_APMATERNO) :
                new ObjectParameter("P_APMATERNO", typeof(string));
    
            var p_RUTParameter = p_RUT.HasValue ?
                new ObjectParameter("P_RUT", p_RUT) :
                new ObjectParameter("P_RUT", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROCEDURE_CREAR_CUENTA", p_NOMBRE_USUARIOParameter, p_CONTRASENAParameter, p_TIPO_USUARIOParameter, p_NOMBREParameter, p_APPATERNOParameter, p_APMATERNOParameter, p_RUTParameter, p_RETORNO);
        }
    
        public virtual int PROCEDURE_DISPO_PLATILLOS(Nullable<decimal> p_DIA, Nullable<decimal> p_PLATILLO_ID, ObjectParameter p_RETORNO)
        {
            var p_DIAParameter = p_DIA.HasValue ?
                new ObjectParameter("P_DIA", p_DIA) :
                new ObjectParameter("P_DIA", typeof(decimal));
    
            var p_PLATILLO_IDParameter = p_PLATILLO_ID.HasValue ?
                new ObjectParameter("P_PLATILLO_ID", p_PLATILLO_ID) :
                new ObjectParameter("P_PLATILLO_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROCEDURE_DISPO_PLATILLOS", p_DIAParameter, p_PLATILLO_IDParameter, p_RETORNO);
        }
    
        public virtual int PROCEDURE_INSERT_PLANILLA(Nullable<decimal> p_ID, Nullable<decimal> p_CONVENIO_ID, string p_RUTA)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("P_ID", p_ID) :
                new ObjectParameter("P_ID", typeof(decimal));
    
            var p_CONVENIO_IDParameter = p_CONVENIO_ID.HasValue ?
                new ObjectParameter("P_CONVENIO_ID", p_CONVENIO_ID) :
                new ObjectParameter("P_CONVENIO_ID", typeof(decimal));
    
            var p_RUTAParameter = p_RUTA != null ?
                new ObjectParameter("P_RUTA", p_RUTA) :
                new ObjectParameter("P_RUTA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROCEDURE_INSERT_PLANILLA", p_IDParameter, p_CONVENIO_IDParameter, p_RUTAParameter);
        }
    
        public virtual int PROCEDURE_REALIZAR_PEDIDO(Nullable<decimal> p_FORMA_PAGO, Nullable<decimal> p_CANTIDAD_PLATILLOS, string p_PEDIDO_DIRECCION, Nullable<decimal> p_PLATILLO_ID, Nullable<decimal> p_CLIENTE_ID, ObjectParameter p_RETORNO)
        {
            var p_FORMA_PAGOParameter = p_FORMA_PAGO.HasValue ?
                new ObjectParameter("P_FORMA_PAGO", p_FORMA_PAGO) :
                new ObjectParameter("P_FORMA_PAGO", typeof(decimal));
    
            var p_CANTIDAD_PLATILLOSParameter = p_CANTIDAD_PLATILLOS.HasValue ?
                new ObjectParameter("P_CANTIDAD_PLATILLOS", p_CANTIDAD_PLATILLOS) :
                new ObjectParameter("P_CANTIDAD_PLATILLOS", typeof(decimal));
    
            var p_PEDIDO_DIRECCIONParameter = p_PEDIDO_DIRECCION != null ?
                new ObjectParameter("P_PEDIDO_DIRECCION", p_PEDIDO_DIRECCION) :
                new ObjectParameter("P_PEDIDO_DIRECCION", typeof(string));
    
            var p_PLATILLO_IDParameter = p_PLATILLO_ID.HasValue ?
                new ObjectParameter("P_PLATILLO_ID", p_PLATILLO_ID) :
                new ObjectParameter("P_PLATILLO_ID", typeof(decimal));
    
            var p_CLIENTE_IDParameter = p_CLIENTE_ID.HasValue ?
                new ObjectParameter("P_CLIENTE_ID", p_CLIENTE_ID) :
                new ObjectParameter("P_CLIENTE_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROCEDURE_REALIZAR_PEDIDO", p_FORMA_PAGOParameter, p_CANTIDAD_PLATILLOSParameter, p_PEDIDO_DIRECCIONParameter, p_PLATILLO_IDParameter, p_CLIENTE_IDParameter, p_RETORNO);
        }
    
        public virtual int PROCEDURE_ELIMINAR_DISPO(Nullable<decimal> p_DIA_ID, Nullable<decimal> p_PLATILLO_ID, ObjectParameter p_RETORNO)
        {
            var p_DIA_IDParameter = p_DIA_ID.HasValue ?
                new ObjectParameter("P_DIA_ID", p_DIA_ID) :
                new ObjectParameter("P_DIA_ID", typeof(decimal));
    
            var p_PLATILLO_IDParameter = p_PLATILLO_ID.HasValue ?
                new ObjectParameter("P_PLATILLO_ID", p_PLATILLO_ID) :
                new ObjectParameter("P_PLATILLO_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROCEDURE_ELIMINAR_DISPO", p_DIA_IDParameter, p_PLATILLO_IDParameter, p_RETORNO);
        }
    
        public virtual int PROCEDURE_CREAR_PLATILLO(Nullable<decimal> p_VALOR, Nullable<decimal> p_TIEMPO_PREPARACION, string p_DESCRIPCION, string p_SRC, string p_NOMBRE, ObjectParameter p_RETORNO)
        {
            var p_VALORParameter = p_VALOR.HasValue ?
                new ObjectParameter("P_VALOR", p_VALOR) :
                new ObjectParameter("P_VALOR", typeof(decimal));
    
            var p_TIEMPO_PREPARACIONParameter = p_TIEMPO_PREPARACION.HasValue ?
                new ObjectParameter("P_TIEMPO_PREPARACION", p_TIEMPO_PREPARACION) :
                new ObjectParameter("P_TIEMPO_PREPARACION", typeof(decimal));
    
            var p_DESCRIPCIONParameter = p_DESCRIPCION != null ?
                new ObjectParameter("P_DESCRIPCION", p_DESCRIPCION) :
                new ObjectParameter("P_DESCRIPCION", typeof(string));
    
            var p_SRCParameter = p_SRC != null ?
                new ObjectParameter("P_SRC", p_SRC) :
                new ObjectParameter("P_SRC", typeof(string));
    
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("P_NOMBRE", p_NOMBRE) :
                new ObjectParameter("P_NOMBRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROCEDURE_CREAR_PLATILLO", p_VALORParameter, p_TIEMPO_PREPARACIONParameter, p_DESCRIPCIONParameter, p_SRCParameter, p_NOMBREParameter, p_RETORNO);
        }
    }
}
