//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PEDIDO()
        {
            this.PEDIDO_PLATILLO = new HashSet<PEDIDO_PLATILLO>();
        }
    
        public byte PEDIDO_ID { get; set; }
        public byte FORMA_PAGO_ID { get; set; }
        public byte ESTADO_ID { get; set; }
        public string DIRECCION { get; set; }
        public System.DateTime HORA_PEDIDO { get; set; }
        public System.DateTime HORA_ENTREGA { get; set; }
    
        public virtual ESTADO_PEDIDO ESTADO_PEDIDO { get; set; }
        public virtual FORMA_PAGO FORMA_PAGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO_PLATILLO> PEDIDO_PLATILLO { get; set; }
    }
}
