//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO_PLATILLO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PEDIDO_PLATILLO()
        {
            this.CLIENTE_PEDIDO = new HashSet<CLIENTE_PEDIDO>();
        }
    
        public byte PEDIDO_PLATILLO_ID { get; set; }
        public byte PEDIDO_ID { get; set; }
        public byte PLATILLO_ID { get; set; }
        public byte CANTIDAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_PEDIDO> CLIENTE_PEDIDO { get; set; }
        public virtual PEDIDO PEDIDO { get; set; }
        public virtual PLATILLO PLATILLO { get; set; }
    }
}
