//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLATILLO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PLATILLO()
        {
            this.DIA_PLATILLO = new HashSet<DIA_PLATILLO>();
            this.PEDIDO_PLATILLO = new HashSet<PEDIDO_PLATILLO>();
        }
    
        public byte PLATILLO_ID { get; set; }
        public short VALOR { get; set; }
        public byte PROMEDIO_PREPARACION { get; set; }
        public string DESCRIPCION { get; set; }
        public string SRC { get; set; }
        public string NOMBRE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIA_PLATILLO> DIA_PLATILLO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO_PLATILLO> PEDIDO_PLATILLO { get; set; }
    }
}
